version: '3.3'

services:
  app:
    build:
      args:
        user: abono-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: abono-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated
    networks:
      - abono

  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
      # If you want to persist data on the host, comment the line above this one...
      # and uncomment the line under this one.
      #- ./docker-compose/db/data:/var/lib/mysql:rw,delegated
    environment:
      MYSQL_USER: abono
      MYSQL_PASSWORD: abono
      MYSQL_DATABASE: abono
      MYSQL_ROOT_PASSWORD: abono
    ports:
      - '33007:3306'
    networks:
      - abono

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 8083:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - abono

  adminer_container:
    image: adminer:latest
    environment: 
        ADMINER_DEFAULT_SERVER: db
        ADMINER_DESIGN: galkaev
    ports: 
      - 5007:8080
    networks:
      - abono


volumes:
  db:

networks:
  abono:
    driver: bridge
