name: CI
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: config0
        run: cp .env.example .env 
      - name: config
        run: chmod -R 775 ./ 
      - name: Build the stack
        run: docker-compose up -d --build
      - name: setup
        run: ./docker-compose/setup.sh
